# homelab/docker-compose.yml
name: homelab-infrastructure

include:
  # Hub Services (Core)
   - path: hub/authentik/docker-compose.yml
   - path: hub/cloudflared/docker-compose.yml
   - path: hub/gatus/docker-compose.yml
   - path: hub/netdata/docker-compose.yml
   - path: hub/traefik/docker-compose.yml
   - path: hub/whoami/docker-compose.yml
  # Spoke Services (Applications)
  # - path: spokes/stirlingpdf/docker-compose.yml
  # - path: spokes/calcom/docker-compose.yml
   - path: spokes/nextcloud/docker-compose.yml
   - path: spokes/paperless/docker-compose.yml
