---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- greeting:
    text_size: xl
    text: "Homepage"

- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true
