# docker-compose.yml
services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dash.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik-dash.service=api@internal
      - traefik.http.routers.traefik-dash.entrypoints=websecure
      - traefik.http.routers.traefik-dash.tls=true
      - traefik.http.routers.traefik-dash.tls.certresolver=cloudflare
      - traefik.http.routers.traefik-dash.middlewares=authentik@file
      - kuma.traefik.http.name=Traefik
      - kuma.traefik.http.url=https://traefik.${DOMAIN_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/certs/:/var/traefik/certs/:rw
      - ./config/conf/:/etc/traefik/conf/:ro
    networks:
      - traefik-frontend
networks:
  traefik-frontend:
    external: true