services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.0
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    healthcheck:
      test: [ CMD, curl, -f, http://localhost:3001 ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuma.rule=Host(`kuma.${DOMAIN_NAME}`)
      - traefik.http.routers.kuma.entrypoints=websecure
      - traefik.http.routers.kuma.tls=true
      - traefik.http.routers.kuma.tls.certresolver=cloudflare
      - traefik.http.routers.kuma.middlewares=authentik@docker
    networks:
      - kuma-backend
      - traefik-frontend

  autokuma:
    image: ghcr.io/bigboot/autokuma:latest
    container_name: uptime-kuma-autokuma
    restart: unless-stopped
    environment:
      - AUTOKUMA__KUMA__URL=http://uptime-kuma:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      uptime-kuma:
        condition: service_healthy
    networks:
      - kuma-backend

networks:
  kuma-backend:
    internal: true
  traefik-frontend:
    external: true
