# docker-compose.yml
services:
  whoami:
    image: traefik/whoami
    container_name: traefik-whoami
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME}`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=cloudflare
      - traefik.http.routers.whoami.middlewares=authentik@file
      - kuma.whoami.http.name=Whoami
      - kuma.whoami.http.url=https://whoami.${DOMAIN_NAME}
    networks:
      - traefik_frontend
networks:
  traefik_frontend:
    external: true