services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.${DOMAIN_NAME}
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`homepage.${DOMAIN_NAME}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=cloudflare
      - traefik.http.routers.homepage.middlewares=authentik@docker
    networks:
      - gatus-backend
      - traefik-frontend

networks:
  gatus-backend:
  traefik-frontend:
    external: true
